### ISSUE TITLE
workflow icons are not displayed

### ISSUE THREAD

**Issue by muescha** [shawnrice/alfred2-workflow-help#4]
workflow icons are not displayed in Quicklook

if i generate the output of the preview then icons are displayed in the result Preview.html in firefox:

```
muescha$ pwd
/Users/muescha/Dropbox/Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B438CBDE-6076-4E15-B5C6-BA5E665ADA54
muescha$ mkdir log
muescha$ qlmanage -p "/Users/muescha/Library/Application Support/Alfred 2/Workflow Data/com.help.shawn.rice/alfred-help.md" -c .md -g libraries/QLMarkdown.qlgenerator -o log
muescha$ open log/alfred-help.md.qlpreview/Preview.html 
```

**Comment by shawnrice** [comment]
You're right. This had to be an error created via an upgrade to Mavericks because it used to work for me and now it doesn't. I'll commit the pull request to fix it for now.

I've re-written most of the workflow for a complete overhaul to make it much nicer overall in both aesthetics, performance, options, and extensibility. I'll make sure that this issue doesn't pop up in the newer version.
